### ISSUE TITLE
A review

### ISSUE THREAD

**Issue by aleos-dev** [shinchik17/weather-app#1]
### [`Locations`Table](https://github.com/shinchik17/weather-app/blob/5e1de41ff4cc789ac0b59020a8ef07a13d811b6d/src/main/resources/db/migration/V2__Create_locations_table.sql) 

- **Latitude and Longitude Precision**: The current precision for latitude and longitude fields might be excessive. Using `DOUBLE PRECISION` is generally sufficient for storing coordinates with acceptable accuracy.
  
- **Indexing and Constraints**:

  - The unique constraint `UNIQUE (user_id, latitude, longitude)` automatically creates an index. Therefore, additional indexes on `(user_id)` are redundant, as the composite index can be used for searches involving `user_id`.
  - An index on `(latitude, longitude)` would be useful for searching specific locations regardless of the user. However, since locations are tied to specific users in this context, this may not be necessary.

### [`sessions` Table](https://github.com/shinchik17/weather-app/blob/5e1de41ff4cc789ac0b59020a8ef07a13d811b6d/src/main/resources/db/migration/V4__Create_sessions_table.sql)

- **Unique Constraint on `user_id`**:

  - The `UNIQUE` constraint on `user_id` allows only one session per user, preventing users from being logged in on more than one device simultaneously. I suppose it is not what you want.
  - This constraint also generates an index on `user_id`, so there's no need to explicitly create an additional index in subsequent migrations.

### [Password Field in `users` Table](https://github.com/shinchik17/weather-app/blob/5e1de41ff4cc789ac0b59020a8ef07a13d811b6d/src/main/resources/db/migration/V1__Create_users_table.sql)
 - Using `VARCHAR` without a strict limit supports algorithm adaptability and has minimal storage impact, so I prefer not to set a limit on the password hash. I’ve already encountered issues with strict limits before.

---

### [`BaseRepository`](https://github.com/shinchik17/weather-app/blob/5e1de41ff4cc789ac0b59020a8ef07a13d811b6d/src/main/java/com/alexshin/weatherapp/repository/BaseRepository.java)

- **Abstract Class**: Consider making `BaseRepository` an abstract class to prevent direct instantiation.

- **`update` Method**:

  - Ensure that an exception is thrown if there is nothing to update, to alert the caller of unsuccessful operations.

- **`delete` Method**:

  - The following implementation reduces the database hits:

    ```java
    @Override
    public void delete(K id) {
        runWithinTx(session -> {
            try {
                E entityRef = session.getReference(clazz, id);
                session.remove(entityRef);
            } catch (EntityNotFoundException e) {
                // Optionally handle the case where the entity doesn’t exist
            }
        });
    }
    ```

### [`UserRepository`](https://github.com/shinchik17/weather-app/blob/5e1de41ff4cc789ac0b59020a8ef07a13d811b6d/src/main/java/com/alexshin/weatherapp/repository/UserRepository.java)

- **Repeated Try-Catch Logic**:

  - The try-catch block for handling `NoResultException` when calling `getSingleResult()` is repeated across several methods.

    ```java
    try {
        return Optional.of(query.getSingleResult());
    } catch (NoResultException e) {
        return Optional.empty();
    }
    ```

  - **Recommendation**: Consider extracting this error handling into a separate method to reduce duplication.

  - Alternatively, based on your needs for database integrity protection, you might prefer one of these approaches:

    - Using `getResultList()`:

      ```java
      return query.getResultList().stream().findFirst();
      ```

    - Using Hibernate's `uniqueResultOptional()`:

      ```java
      return query.uniqueResultOptional();
      ```

### [`UserSessionRepository`](https://github.com/shinchik17/weather-app/blob/5e1de41ff4cc789ac0b59020a8ef07a13d811b6d/src/main/java/com/alexshin/weatherapp/repository/UserSessionRepository.java)

- **Simplifying Queries**:

  - Queries like:

    ```java
    String sqlString = """
        DELETE FROM UserSession s
        WHERE s.user in
            (FROM User
            WHERE login = :login)
        """;
    ```

  - Can be simplified to:

    ```java
    session.createQuery("DELETE FROM UserSession s WHERE s.user.login = :login")
    ```

---

### Schema Definitions in Entities

Defining database schema details ([like indexes or foreign keys](https://github.com/shinchik17/weather-app/blob/5e1de41ff4cc789ac0b59020a8ef07a13d811b6d/src/main/java/com/alexshin/weatherapp/model/entity/Location.java#L16)) in entity classes can become redundant and potentially problematic, especially when using tools like Flyway for database migrations. Changes in the database schema may not be reflected in the entity definitions if not maintained consistently, leading to confusion or errors.

Avoid duplicating schema definitions in the codebase if Hibernate is not used for DDL operations. Instead, use the migration files as the single source of truth for the database schema.

### [But, Field Annotations Are Still Useful](https://github.com/shinchik17/weather-app/blob/5e1de41ff4cc789ac0b59020a8ef07a13d811b6d/src/main/java/com/alexshin/weatherapp/model/entity/User.java#L20C2-L21C26)

Despite avoiding schema duplication, certain field annotations in entity classes remain valuable. They provide a clear overview of the data model within the code and influence Hibernate's runtime behavior.

- **Improving Readability and Understanding**: Annotations like `@Column(nullable = false)` or `@Column(unique = true)` help developers quickly understand the constraints and requirements of each field.

- **Affecting Hibernate's Behavior**:

  - **`nullable = false`**:

    - Influences query generation, potentially leading Hibernate to use `INNER JOIN` instead of `LEFT JOIN` for associations, optimizing performance by excluding `null` values.

  - **`@NaturalId`**:

    - Allows Hibernate to recognize a field as a unique identifier outside of the primary key.
    - Enables caching and efficient retrieval based on the natural ID.

  - **Hibernate Validation Annotations**:

    - Annotations like `@NotNull`, `@Size`, and `@Min` provide immediate data integrity checks before persisting to the database.

#### Practical vs. Redundant Annotations

| Annotation                             | Practical for Application | Redundant if Managed by Migrations |
|----------------------------------------|---------------------------|------------------------------------|
| `@Column(nullable = false)`            | Yes                       | No                                 |
| `@JoinColumn(nullable = false)`        | Yes                       | No                                 |
| `@Column(unique = true)`               | Yes                       | No                                 |
| `@Column(precision = ..., scale = ...)`| Optional                  | No                                 |
| `@Index`                               | No                        | Yes                                |
| `@Table(uniqueConstraints = {...})`    | No                        | Yes                                |
| `@Table(schema = "public")`            | Optional                  | Yes (unless for multi-schema clarity) |

### [`UserSession` Entity](https://github.com/shinchik17/weather-app/blob/5e1de41ff4cc789ac0b59020a8ef07a13d811b6d/src/main/java/com/alexshin/weatherapp/model/entity/UserSession.java)

1. **Use `UUID` for `id`**:

   - Since PostgreSQL natively supports the `UUID` type, it's better to use `UUID` directly instead of converting it to a `String`. This approach leverages PostgreSQL's optimizations for UUIDs.

2. **Use `Instant` for `expiresAt`**:

   - `expiresAt` represents a specific point in time. Using `Instant` (which is always in UTC) avoids issues with time zones and daylight saving time changes, ensuring consistent behavior across different locations.

---

### [`UserService`](https://github.com/shinchik17/weather-app/blob/5e1de41ff4cc789ac0b59020a8ef07a13d811b6d/src/main/java/com/alexshin/weatherapp/service/UserService.java)

The [`save` method](https://github.com/shinchik17/weather-app/blob/5e1de41ff4cc789ac0b59020a8ef07a13d811b6d/src/main/java/com/alexshin/weatherapp/service/UserService.java#L25) in `UserService` currently catches `BaseRepositoryException` and rethrows it as `SuchUserExistsException` if the cause is a `ConstraintViolationException`. This exception handling occurs too early in the service layer. Since it's merely wrapping and rethrowing the exception, it's better to handle it directly in `UserRepository` or on a higher level. 

**Suggested Refactor**: Catch and handle `ConstraintViolationException` in `[UserRepository](https://github.com/shinchik17/weather-app/blob/5e1de41ff4cc789ac0b59020a8ef07a13d811b6d/src/main/java/com/alexshin/weatherapp/repository/UserRepository.java#L10)` to simplify the `save` method in `UserService`.

```java
// UserRepository.java
public void save(User user) {
    try {
        super.save(user);
    } catch (ConstraintViolationException e) {
        throw new SuchUserExistsException(
                "User with login %s is already registered".formatted(user.getLogin()), e
        );
    }
}
```

#### Use of DTO in `save` Method

The `save` method should accept a **DTO (Data Transfer Object)** rather than the entity itself, especially if mapping isn't done at the servlet layer. This practice promotes separation of concerns and prevents direct exposure of entity classes to higher layers.

#### Necessity of `UserService`

`UserService` is only used within other [service classes](https://github.com/shinchik17/weather-app/blob/5e1de41ff4cc789ac0b59020a8ef07a13d811b6d/src/main/java/com/alexshin/weatherapp/service/RegistrationService.java#L21) and isn't exposed to the controller layer. It essentially acts as a wrapper around `UserRepository`. In this case, it might be unnecessary, and other service classes could interact directly with `UserRepository`, reducing code complexity.

### [`AuthenticationService`](https://github.com/shinchik17/weather-app/blob/5e1de41ff4cc789ac0b59020a8ef07a13d811b6d/src/main/java/com/alexshin/weatherapp/service/AuthenticationService.java#L16)

1. [**User Existence Check**](https://github.com/shinchik17/weather-app/blob/5e1de41ff4cc789ac0b59020a8ef07a13d811b6d/src/main/java/com/alexshin/weatherapp/service/AuthenticationService.java#L33):

   Original Code:

   ```java
   Optional<User> user = userService.findByLogin(userDTO.getLogin());
   if (user.isEmpty()) {
       throw new NoSuchUserException("No user with login '%s' registered".formatted(userDTO.getLogin()));
   }
   ```

   Improved Code:

   ```java
   User user = userService.findByLogin(userDTO.getLogin())
           .orElseThrow(() -> new NoSuchUserException("No user with login '%s' registered".formatted(userDTO.getLogin())));
   ```

2. *[*Session Creation or Retrieval**:](https://github.com/shinchik17/weather-app/blob/5e1de41ff4cc789ac0b59020a8ef07a13d811b6d/src/main/java/com/alexshin/weatherapp/service/AuthenticationService.java#L42)

   Original Code:

   ```java
   Optional<UserSession> userSession = userSessionService.findByUserLogin(userDTO.getLogin());

   if (userSession.isEmpty()) {
       userSession = Optional.of(userSessionService.createSession(user.get()));
   }
   ```

   Improved Code (no needs for the Optional):

   ```java
   UserSession userSession = userSessionService.findByUserLogin(userDTO.getLogin())
           .orElseGet(() -> userSessionService.createSession(user));
   ```

---
### Exception Handling

- **[Catching General Exceptions](https://github.com/shinchik17/weather-app/blob/5e1de41ff4cc789ac0b59020a8ef07a13d811b6d/src/main/java/com/alexshin/weatherapp/servlet/HomeServlet.java#L47)**: Catching a general `Exception` is not a good practice, as it can obscure specific errors and make debugging difficult.
- **[Ignoring Exceptions in `handleExceptions`](https://github.com/shinchik17/weather-app/blob/5e1de41ff4cc789ac0b59020a8ef07a13d811b6d/src/main/java/com/alexshin/weatherapp/servlet/HomeServlet.java#L96)**:
  - In `[SearchLocationServlet](https://github.com/shinchik17/weather-app/blob/5e1de41ff4cc789ac0b59020a8ef07a13d811b6d/src/main/java/com/alexshin/weatherapp/servlet/SearchLocationServlet.java#L99)`, some exceptions are ignored without logging.
  - In `[AuthServlet](https://github.com/shinchik17/weather-app/blob/5e1de41ff4cc789ac0b59020a8ef07a13d811b6d/src/main/java/com/alexshin/weatherapp/servlet/AuthServlet.java#L16)`, exception details are lost, retaining only the message, which is insufficient for developers.
- **Multiple Exception Handling Points**: You have multiple points where exceptions are handled. While this approach provides precise control over client responses, it can appear messy and difficult to maintain. Honestly, it takes time to understand the flow. Using a central handler, such as through filters or a base servlet, offers a more convenient and cleaner way to manage exceptions. Although centralizing may trade off some customization, I believe this isn't a concern with your current code structure.
### Response Handling After Exceptions

- **[Improper Use of `resp.sendRedirect`](https://github.com/shinchik17/weather-app/blob/5e1de41ff4cc789ac0b59020a8ef07a13d811b6d/src/main/java/com/alexshin/weatherapp/servlet/SearchLocationServlet.java#L83)**:
    A template engine like Thymeleaf composes the response and writes it using a `PrintWriter`, but then the stack unwinds until it reaches `resp.sendRedirect(rootPath)`. At this moment, an HTTP 302 redirect response is triggered, which overwrites the current buffered content. This is likely not the behavior you want.
```java
    } catch (Exception e) {
        handleExceptions(e, req, resp);
    }
    resp.sendRedirect(rootPath);
```

## SearchLocationServlet

- **[Redundant Authentication Logic](https://github.com/shinchik17/weather-app/blob/5e1de41ff4cc789ac0b59020a8ef07a13d811b6d/src/main/java/com/alexshin/weatherapp/servlet/SearchLocationServlet.java#L67)**:
  - In `doPost`, you extract the authentication object:
   ```java
              String sessionId = CookieUtil.extractSessionCookie(req).orElseThrow(AuthenticationException::new);
            UserDTO user = authService.findUserBySessionId(sessionId).orElseThrow(AuthenticationException::new);
   ```
 - **Issue**: The `[ProtectedUrlFilter](https://github.com/shinchik17/weather-app/blob/5e1de41ff4cc789ac0b59020a8ef07a13d811b6d/src/main/java/com/alexshin/weatherapp/filter/ProtectedUrlFilter.java#L45)` already performs this authentication and sets the user in the request.

## [HomeServlet](https://github.com/shinchik17/weather-app/blob/5e1de41ff4cc789ac0b59020a8ef07a13d811b6d/src/main/java/com/alexshin/weatherapp/servlet/HomeServlet.java)
- **Authorization Logic**:
  - It would be nice using `[locService.deleteByUser(userId, locId)](https://github.com/shinchik17/weather-app/blob/5e1de41ff4cc789ac0b59020a8ef07a13d811b6d/src/main/java/com/alexshin/weatherapp/servlet/HomeServlet.java#L68);` to encapsulate the authorization check within the service layer.
  - **Benefits**:
    - Eliminates the need to check ownership in the servlet.
    - Simplifies the servlet code and improves security.
    - You don't need SC_FORBIDDEN, as the user has such a location or not... 
  - **HTTP Status Codes**:
    - Recommend using `204 No Content` instead of `200 OK` for successful DELETE operations, as it is more appropriate and aligns with RESTful conventions.
```java
protected void doDelete(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
    UserDTO user = (UserDTO) req.getAttribute("user");
    DeleteRequest deleteRequest = parseDeleteRequest(req);

    boolean deleted = locService.deleteByUser(user.getId(), deleteRequest.getLocationId());

    if (deleted) {
        resp.setStatus(HttpServletResponse.SC_NO_CONTENT); // 204 No Content
    } else {
        resp.setStatus(HttpServletResponse.SC_NOT_FOUND); // 404 Not Found
    }
}

```

## [LogoutServlet](https://github.com/shinchik17/weather-app/blob/5e1de41ff4cc789ac0b59020a8ef07a13d811b6d/src/main/java/com/alexshin/weatherapp/servlet/LogOutServlet.java)

- **Avoid Parsing Parameters for Logout**:
  - Currently parses the `login` parameter from the request, which can be manipulated.
  - **Recommendation**:
    - Use the authenticated user object provided by the `ProtectedUrlFilter`.
    - Improves security by relying on server-side session data rather than client-supplied parameters.

# [Filters](https://github.com/shinchik17/weather-app/tree/5e1de41ff4cc789ac0b59020a8ef07a13d811b6d/src/main/java/com/alexshin/weatherapp/filter)

Since you declare filters using annotations, their order may indeed vary each time you restart the server. This means that [BaseFilter](https://github.com/shinchik17/weather-app/blob/5e1de41ff4cc789ac0b59020a8ef07a13d811b6d/src/main/java/com/alexshin/weatherapp/filter/BaseFilter.java#L17), which is supposed to be the front filter for access restriction to URLs, could end up being called last in the filter chain. To ensure consistent ordering, consider registering filters in `web.xml` or dynamically  with listeners to guarantee this filter is called first.

Additionally, the `SessionId` check ([1](https://github.com/shinchik17/weather-app/blob/5e1de41ff4cc789ac0b59020a8ef07a13d811b6d/src/main/java/com/alexshin/weatherapp/filter/AuthFilter.java#L27), [2](https://github.com/shinchik17/weather-app/blob/5e1de41ff4cc789ac0b59020a8ef07a13d811b6d/src/main/java/com/alexshin/weatherapp/filter/HomeFilter.java#L27), [3](https://github.com/shinchik17/weather-app/blob/5e1de41ff4cc789ac0b59020a8ef07a13d811b6d/src/main/java/com/alexshin/weatherapp/filter/ProtectedUrlFilter.java#L28))is duplicated across multiple filters, along with retrieving user information through `authService` ([1](https://github.com/shinchik17/weather-app/blob/5e1de41ff4cc789ac0b59020a8ef07a13d811b6d/src/main/java/com/alexshin/weatherapp/filter/ProtectedUrlFilter.java#L36), [2](https://github.com/shinchik17/weather-app/blob/5e1de41ff4cc789ac0b59020a8ef07a13d811b6d/src/main/java/com/alexshin/weatherapp/filter/HomeFilter.java#L35)). I would suggest handling this in a single filter and placing the result in an `AuthenticationHolder`, so other filters and servlets can simply use this result.

## Conclusion
Although there are areas that can be enhanced—such as exception handling, filter usage, and addressing issues with multiple spaces abusing— you have managed to keep your project simple and readable despite utilizing multiple technologies. Your custom build configuration of Hibernate, along with the integration of Prometheus and Grafana, adds a unique touch to your project. The codebase is generally clean and follows good practices.

Keep up the great work, and continue striving for excellence in your code!

**Comment by shinchik17** [comment]
## Database Migrations

### Locations and sessions tables

> **Latitude and Longitude Precision**: The current precision for latitude and longitude fields might be excessive. Using
`DOUBLE PRECISION` is generally sufficient for storing coordinates with acceptable accuracy.

Genereally double preciscion is sufficient but not always. For example for another API which provides more accurate locations coords. So it's discussable moment imho.

- **Indexing and Constraints**:

Just wanted to make indexes names clear. Another my goal was to make possible understanding of FULL structure and constraints of the table by checking single dedicated file. That's why I created additional named indexes. Maybe the better choice is to create named unique indexes.

> The `UNIQUE` constraint on `user_id` allows only one session per user, preventing users from being logged in on more than
one device simultaneously. I suppose it is not what you want.

Not sure it would prevent users to be logged on multiple devices simultaneously but logging out on one device guaranteedly wil result in logging out from all devices :D That's not what I want, that's true

### Password field users table
> Using `VARCHAR` without a strict limit supports algorithm adaptability and has minimal storage impact, so I prefer not to set
a limit on the password hash. I’ve already encountered issues with strict limits before.

Thats's discussable too. I have never encountered issues with strict limits on passwords hash. The maximum length of BCypt hash is known, so I can't imagine problems here.

## Repository layer
The only things I have to comment:

> * **Simplifying Queries**:
>   
>   * Queries like:
>     ```java
>     String sqlString = """
>         DELETE FROM UserSession s
>         WHERE s.user in
>             (FROM User
>             WHERE login = :login)
>         """;
>     ```
>   * Can be simplified to:
>     ```java
>     session.createQuery("DELETE FROM UserSession s WHERE s.user.login = :login")
>     ```

The simplified version of such queries didn't work. I don't remember what I exactly got from error stacktrace but smth like "unresolved reference .." or "cannot foud ..". That was surprise for me, because I used such simple queries in previous project. But I skipped it after long tries to find the reason.

## Entities

Just thanks for such an exchaustive hibernate annotations describing. I'm not so into topic :)


## Services

> `UserService` is only used within other [service classes](https://github.com/shinchik17/weather-app/blob/5e1de41ff4cc789ac0b59020a8ef07a13d811b6d/src/main/java/com/alexshin/weatherapp/service/RegistrationService.java#L21) and isn't exposed to the controller layer. It essentially acts as a wrapper around `UserRepository`. In this case, it might be unnecessary, and other service classes could interact directly with `UserRepository`, reducing code complexity.

As for me, precence of UserService provides consistency. Three entities -> three services which incapsulate crud operations -> three repository. It's quite easy to navigate through such structure, imho


> 1. Original Code:
>    ```java
>    Optional<User> user = userService.findByLogin(userDTO.getLogin());
>    if (user.isEmpty()) {
>        throw new NoSuchUserException("No user with login '%s' registered".formatted(userDTO.getLogin()));
>    }
>    ```
>    Improved Code:
>    ```java
>    User user = userService.findByLogin(userDTO.getLogin())
>            .orElseThrow(() -> new NoSuchUserException("No user with login '%s' registered".formatted(userDTO.getLogin())))
>    ```

As for me Stream API here damages readability, imho


## Servlets

> Catching a general `Exception` is not a good practice, as it can obscure specific errors and make debugging difficult.

Do you think it's better to send user default Tomcat 505 Internal Server Error page instead of main page with message "Service error. Please try again later"? I consider my way is more user-friendly. It may make debugging more difficult I realize that and nevertheless prefer user-fdriendly approach.

> **[Ignoring Exceptions in `handleExceptions`](https://github.com/shinchik17/weather-app/blob/5e1de41ff4cc789ac0b59020a8ef07a13d811b6d/src/main/java/com/alexshin/weatherapp/servlet/HomeServlet.java#L96)**:
> * In `[SearchLocationServlet](https://github.com/shinchik17/weather-app/blob/5e1de41ff4cc789ac0b59020a8ef07a13d811b6d/src/main/java/com/alexshin/weatherapp/servlet/SearchLocationServlet.java#L99)`, some exceptions are ignored without logging.

All exceptions are logging at  [line 99](https://github.com/shinchik17/weather-app/blob/5e1de41ff4cc789ac0b59020a8ef07a13d811b6d/src/main/java/com/alexshin/weatherapp/servlet/SearchLocationServlet.java#L89)


> * In `[AuthServlet](https://github.com/shinchik17/weather-app/blob/5e1de41ff4cc789ac0b59020a8ef07a13d811b6d/src/main/java/com/alexshin/weatherapp/servlet/AuthServlet.java#L16)`, exception details are lost, retaining only the message, which is insufficient for developers.

As for me, [this is enough](https://github.com/shinchik17/weather-app/blob/5e1de41ff4cc789ac0b59020a8ef07a13d811b6d/src/main/java/com/alexshin/weatherapp/servlet/AuthServlet.java#L10)  since it contains "Cause" info and "Message" is customized by custom exceptions which extend IllegalArgumentException


> Since you declare filters using annotations, their order may indeed vary each time you restart the server. This means that [BaseFilter](https://github.com/shinchik17/weather-app/blob/5e1de41ff4cc789ac0b59020a8ef07a13d811b6d/src/main/java/com/alexshin/weatherapp/filter/BaseFilter.java#L17), which is supposed to be the front filter for access restriction to URLs, could end up being called last in the filter chain. To ensure consistent ordering, consider registering filters in `web.xml` or dynamically with listeners to guarantee this filter is called first.

Discussable. I have never encounter issues with filter order since the rule "the more wide filder mapping is the earlier it appears in filter chain". Of course, direct registering filters gives much clearer view of filter chain. But it's not what I was interested to learn in this project. It's too easy :D


> Additionally, the `SessionId` check ([1](https://github.com/shinchik17/weather-app/blob/5e1de41ff4cc789ac0b59020a8ef07a13d811b6d/src/main/java/com/alexshin/weatherapp/filter/AuthFilter.java#L27), [2](https://github.com/shinchik17/weather-app/blob/5e1de41ff4cc789ac0b59020a8ef07a13d811b6d/src/main/java/com/alexshin/weatherapp/filter/HomeFilter.java#L27), [3](https://github.com/shinchik17/weather-app/blob/5e1de41ff4cc789ac0b59020a8ef07a13d811b6d/src/main/java/com/alexshin/weatherapp/filter/ProtectedUrlFilter.java#L28))is duplicated across multiple filters, along with retrieving user information through `authService` ([1](https://github.com/shinchik17/weather-app/blob/5e1de41ff4cc789ac0b59020a8ef07a13d811b6d/src/main/java/com/alexshin/weatherapp/filter/ProtectedUrlFilter.java#L36), [2](https://github.com/shinchik17/weather-app/blob/5e1de41ff4cc789ac0b59020a8ef07a13d811b6d/src/main/java/com/alexshin/weatherapp/filter/HomeFilter.java#L35)). I would suggest handling this in a single filter and placing the result in an `AuthenticationHolder`, so other filters and servlets can simply use this result.

As I said before, I used only mappings for filters. Thats's why filter chain more resembles "filter tree", which means that some filters may take part in certain request handling. For example, if it's request to login or register page and there is a session cookie I don't need to use AuthService, just redirect to root. And some other unclear cases are handled by such structure. Of course, if I would't have a goal to learn filter mappings, I'd use a single filter for authentication stuff. Fortunately, I have Spring Security now :D


## Conclusion

Although there are comments I don't agree with — such as partitially exception handling, "improving" code with Stream API features and filters order issues — you made a huge effort and spent a lot of time (I suppose so because the mere answering on it took a few hours of me) on reviewing my project. All the points I don't mentioned in my reply are mostly justice and reasonable and I accede to them. Realy appreciate the job you've done.

Keep up the great work, and continue ~~being a real pain in the ass~~ motivating me and others to strive for excellence in our code!

**Comment by aleos-dev** [comment]
> Genereally double preciscion is sufficient but not always. For example for another API which provides more accurate locations coords. So it's discussable moment IMHO.

Double precision uses 8 bytes and provides variable, inexact precision with approximately 15 decimal digits of accuracy. According to [OpenStreetMap's data](https://wiki.openstreetmap.org/wiki/Precision_of_coordinates), 6 decimal places ensure accuracy to within 0.1 meters.

> Not sure it would prevent users to be logged on multiple devices simultaneously

The user_id is unique in the session table, so there can't be two sessions for the same user.

> The simplified version of such queries didn't work.

This is interesting. I'll test it and get back to you with feedback.

> Do you think it's better to send user default Tomcat 505 Internal Server Error page instead of main page with message "Service error. Please try again later"?

What I mean is that global exception handling should be centralized in one place. You have multiple handlers that repeat the same logic, and regardless of where the exception is caught, such a global error message will be shown on different pages like the home page, registration page, etc. I would prefer to display it on a specific page.

---
---

I’m glad to hear that some of the points resonated with you (even if the "exception handling" club didn’t gain a new member this time 😅).

It’s totally fair to have different perspectives on things like Stream API improvements or filter order—sometimes it’s less about "right" or "wrong" and more about personal style or priorities. But hey, disagreement is where the fun (and learning) happens, right?

> Keep up the great work, and continue being a real pain in the ass motivating me and others to strive for excellence in our code!

Glad to know I’m meeting expectations—I'll keep up being an expert-level pain in the ass 😄

**Comment by shinchik17** [comment]
> within 0.1 meters.

SO INACCURATELY 🤯 😆Well, you are right, double is quite enough :)

> The user_id is unique in the session table, so there can't be two sessions for the same user.

If remember my auth logic properly there can be two devices using single session for certain user. After logging on second device app would just add cookie to browser. So you CAN use app on MULTIPLE devices/browsers but with SINGLE session for certain user. That's why I said 

> logging out on one device guaranteedly wil result in logging out from all devices :D That's not what I want, that's true

This implementation is not correct, of course.

> global error message will be shown on different pages like the home page, registration page, etc. I would prefer to display it on a specific page.

I prefer to show error message on page which it related to. If it's possible, of course. So it's just a preference

> expert-level pain in the ass 😄

Absolutely outstanding professional 😎
